<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Dashboard</h3>
  </div>
  <div class="panel-body">
      <div class="col-md-4">
          <img src="<?= $this->url->getStatic('public/images/logo.jpg') ?>" alt="">
      </div>
      <div class="col-md-6 col-md-offset-1">
          <ul class="list-group">
              <li class="list-group-item">Total Responden Alumni <span class="badge"><?= $responden_alumni?></span></li>
              <li class="list-group-item">Total Responden User <span class="badge"><?= $responden_user?></span></li>
              <li class="list-group-item">Total Kuisioner Alumni <span class="badge"><?= $kuisioner_alumni?></span></li>
              <li class="list-group-item">Total Kuisioner User <span class="badge"><?= $kuisioner_user?></span></li>
          </ul>
      </div>
  </div>
  <div class="panel-footer">

  </div>
</div>
